version: "3.9"
services:
  homeassistant:
    container_name: ha
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - 'C:\homeassistant:/config'
    environment:
      - TZ=Europe/Warsaw
#    network_mode: host
    ports:
      - '8123:8123'
    restart: unless-stopped
 
    healthcheck:
      test: 'curl -m 90 -sLf http://localhost:8123 || date >> /config/healthcheck' #| pkill -9 python3'
      interval: 90s
      timeout: 60s
      retries: 2  